/*
 * Travel Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/menakaj/travel/go"
)

func main() {
	fmt.Printf("Server started")

	fmt.Printf("ServiceUrl %s", os.Getenv("PETSTORE_ENDPOINT_URL"))

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8081", router))
}
