/*
 * Travel Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/menakaj/travel/go"
)

func main() {
	log.Printf("Server started")

	log.Printf("ServiceUrl %s", os.Getenv("CHOREO_EMPNEW_SERVICEURL"))
	log.Printf("ClientId %s", os.Getenv("CHOREO_EMPNEW_CLIENTID"))
	log.Printf("ClientSecret %s", os.Getenv("CHOREO_EMPNEW_CLIENTSECRET"))
	log.Printf("TokenUrl %s", os.Getenv("CHOREO_EMPNEW_TOKENURL"))
	log.Println(os.Environ())

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8081", router))
}
